// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Config = { intermediate_width: number, intermediate_height: number, prioritize_unique: boolean, unique_threshold: number, subpixel_size: number, input_path: string | null, library_path: string | null, };
